---
- name: Provision Garry's Mod Server on Ubuntu 22.04
  hosts: gmod_server
  become: yes
  become_method: sudo  # Explicitly set sudo
  become_user: root  # Run as root

  vars:
    gmod_user: gmod
    gmod_dir: /home/gmod/steamcmd
    gmod_appid: 4020
    # rcon_password: Pass this variable via Semaphore or command line with -e rcon_password="your_password"
    # gslt_token: Pass this variable via Semaphore or command line with -e gslt_token="your_gslt_token"
    gmod_servers:
      - name: "PlaZma Gaming - TTT"
        dir: /home/gmod/gmodserver1
        port: 27015
        clientport: 27015
        tv_port: 27020
        gamemode: terrortown
        map: ttt_minecraft_b5
        service_name: gmodserver1
        ip: 10.0.1.100
        workshop_collection_id: 3642346339
      - name: "PlaZma Gaming - Prop Hunt"
        dir: /home/gmod/gmodserver2
        port: 27016
        clientport: 27016
        tv_port: 27021
        gamemode: prophunt
        map: ph_restaurant
        service_name: gmodserver2
        ip: 10.0.1.100
        workshop_collection_id: 3642346339

  tasks:

    - name: Set hostname to gmod
      ansible.builtin.shell: |
        hostnamectl set-hostname gmod || echo "gmod" > /etc/hostname
        hostname gmod
      changed_when: true
      ignore_errors: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - lib32gcc-s1
          - lib32stdc++6
          - software-properties-common
          - curl
          - ca-certificates
        update_cache: yes

    - name: Create gmod user
      ansible.builtin.user:
        name: "{{ gmod_user }}"
        shell: /bin/bash
        home: "/home/{{ gmod_user }}"
        create_home: yes

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        mode: '0755'
      loop:
        - "{{ gmod_dir }}"
        - "{{ gmod_servers[0].dir }}"
        - "{{ gmod_servers[1].dir }}"

    - name: Download SteamCMD
      ansible.builtin.get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: "{{ gmod_dir }}/steamcmd_linux.tar.gz"
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        mode: '0644'

    - name: Extract SteamCMD
      ansible.builtin.unarchive:
        src: "{{ gmod_dir }}/steamcmd_linux.tar.gz"
        dest: "{{ gmod_dir }}"
        remote_src: yes
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        creates: "{{ gmod_dir }}/steamcmd.sh"

    - name: Initialize SteamCMD (let it update itself)
      become: yes
      shell: |
        sudo -u {{ gmod_user }} bash -c "cd {{ gmod_dir }} && ./steamcmd.sh +quit"
      args:
        creates: "{{ gmod_dir }}/linux32/steamclient.so"

    - name: Check if Garry's Mod servers are already installed
      ansible.builtin.stat:
        path: "{{ item.dir }}/srcds_run"
      register: gmod_servers_installed
      loop: "{{ gmod_servers }}"

    - name: Ensure server directories exist with correct permissions
      ansible.builtin.file:
        path: "{{ item.item.dir }}"
        state: directory
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        mode: '0755'
        recurse: yes
      loop: "{{ gmod_servers_installed.results }}"
      when: not item.stat.exists

    - name: Install Garry's Mod servers with SteamCMD
      become: yes
      shell: |
        sudo -u {{ gmod_user }} bash -c "cd {{ gmod_dir }} && ./steamcmd.sh +force_install_dir {{ item.item.dir }} +login anonymous +app_update {{ gmod_appid }} validate +quit"
      loop: "{{ gmod_servers_installed.results }}"
      when: not item.stat.exists
      retries: 5
      delay: 30
      register: install_result
      until: install_result.rc == 0 and install_result.stdout.find('Error!') == -1
      async: 1800
      poll: 30
      failed_when: install_result.rc != 0 or 'Error!' in install_result.stdout

    - name: Display SteamCMD installation output
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ install_result.results }}"
      when: item.changed is defined and item.changed

    - name: Create systemd service files for each server
      copy:
        dest: "/etc/systemd/system/{{ item.service_name }}.service"
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Garry's Mod Server - {{ item.name }}
          After=network.target
    
          [Service]
          Type=simple
          User={{ gmod_user }}
          WorkingDirectory={{ item.dir }}
          ExecStart={{ item.dir }}/srcds_run -game garrysmod +maxplayers 20 +map {{ item.map }} +gamemode {{ item.gamemode }} -port {{ item.port }} +clientport {{ item.clientport }} +tv_port {{ item.tv_port }} +hostname "{{ item.name }}" +sv_setsteamaccount {{ gslt_token }} +ip {{ item.ip }} +host_workshop_collection {{ item.workshop_collection_id }}
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      loop: "{{ gmod_servers }}"
      notify: Reload systemd

    - name: Check if server installation is complete
      ansible.builtin.stat:
        path: "{{ item.dir }}/garrysmod/cfg"
      register: gmod_cfg_dirs
      loop: "{{ gmod_servers }}"

    - name: Ensure garrysmod/cfg directory exists
      ansible.builtin.file:
        path: "{{ item.dir }}/garrysmod/cfg"
        state: directory
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        mode: '0755'
      loop: "{{ gmod_servers }}"

    - name: Deploy server.cfg to each server
      template:
        src: "files/server_{{ item.service_name }}.cfg.j2"
        dest: "{{ item.dir }}/garrysmod/cfg/server.cfg"
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
        mode: '0644'
      loop: "{{ gmod_servers }}"
      notify: Reload systemd

    - name: Check if srcds_run exists for each server
      ansible.builtin.stat:
        path: "{{ item.dir }}/srcds_run"
      register: srcds_run_check
      loop: "{{ gmod_servers }}"

    - name: Ensure srcds_run is executable
      ansible.builtin.file:
        path: "{{ item.item.dir }}/srcds_run"
        mode: '0755'
        owner: "{{ gmod_user }}"
        group: "{{ gmod_user }}"
      loop: "{{ srcds_run_check.results }}"
      when: item.stat.exists
    
    - name: Stop GMod servers before restarting
      ansible.builtin.systemd:
        name: "{{ item.item.service_name }}"
        state: stopped
      loop: "{{ srcds_run_check.results }}"
      when: item.stat.exists
      ignore_errors: yes

    - name: Kill any remaining srcds processes
      ansible.builtin.shell: |
        pkill -9 -f "srcds_run.*{{ item.item.service_name }}" || true
        pkill -9 -f "srcds_linux.*port {{ item.item.port }}" || true
      loop: "{{ srcds_run_check.results }}"
      when: item.stat.exists
      ignore_errors: yes

    - name: Wait for ports to be released
      ansible.builtin.wait_for:
        port: "{{ item.item.port }}"
        state: stopped
        timeout: 30
      loop: "{{ srcds_run_check.results }}"
      when: item.stat.exists
      ignore_errors: yes
    
    - name: Enable and start GMod servers
      ansible.builtin.systemd:
        name: "{{ item.item.service_name }}"
        enabled: true
        state: started
      loop: "{{ srcds_run_check.results }}"
      when: item.stat.exists
    
    # handlers section
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
